---
- name: Write myid file.
  template: src=myid.j2 dest={{data_dir}}/myid owner=zookeeper group=zookeeper
  tags: deploy
  notify:
    - Restart zookeeper

- name: Start zookeeper service
  service: name=zookeeper state=started enabled=yes
  tags: deploy
