---
- include: deb-uninstall.yml
  when: ansible_os_family == 'Debian' and zookeeper_debian_apt_uninstall

- include: Debian.yml
  when: ansible_os_family == 'Debian' and zookeeper_debian_apt_install

- include: Debian-tarball.yml
  when: ansible_os_family == 'Debian' and not zookeeper_debian_apt_install

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
